# Generated by Django 6.0.5 on 2026-06-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
