# Generated by Django 6.0.5 on 2026-06-09 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_payment_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.theater'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie'], name='movies_book_movie_i_71732a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater'], name='movies_book_theater_f50fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='movies_book_user_id_848399_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='movies_paym_status_5316c9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='movies_paym_created_5e9beb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['updated_at'], name='movies_paym_updated_c5e8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='movies_paym_user_id_2b1659_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['theater'], name='movies_paym_theater_18a64c_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater'], name='movies_seat_theater_5b3dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['is_booked'], name='movies_seat_is_book_ae17f5_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['locked_until'], name='movies_seat_locked__e5a3bd_idx'),
        ),
    ]
