# Generated by Django 6.0.5 on 2026-06-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_genre_language_movie_genres_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='movies.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['event_id'], name='movies_paym_event_i_fcbe36_idx'), models.Index(fields=['event_type'], name='movies_paym_event_t_8a3046_idx'), models.Index(fields=['received_at'], name='movies_paym_receive_d6fbae_idx')],
            },
        ),
    ]
